### PR TITLE
Bump: update the version of action/core to v1.10.0 and use node v16

### PR DESCRIPTION
**Pull request by floralatin**

### CODE REVIEW

**Comment by floralatin** [comment]
@svenstaro

**Review by Vucko130 — APPROVED** [review]

**Comment by taysta** [comment]
@svenstaro

**Comment by Revolution1** [comment]
any update?

**Comment by shawaj** [comment]
@svenstaro can this be pulled in?

**Comment by azzamsa** [comment]
His last commit is 2 days ago https://github.com/svenstaro/miniserve/commit/855488941b39a6e366565d6b3ce9baf9292d0aca. I am afraid he muted this repo. I think we need to inform him via email or other platform.

**Comment by shawaj** [comment]
From the commit it has the following details... Sven-Hendrik Haase <svenstaro@gmail.com>

**Comment by svenstaro** [comment]
Guys, I haven't muted anything. I'm rather busy and all my work on open source is time I spend next to my day job and I have quite a few open source projects that I try to maintain but time is limited. I think GitHub Actions are really quite hard to maintain as they are right now as even though it's using TypeScript, I found that only actually running the Action will the real issues. As such, I was in the process of rewriting the Action in Rust in which I'm way more comfortable but again, time is short. I will merge this now and see whether I can find a co-maintainer.

**Comment by svenstaro** [comment]
Actually nevermind, since it doesn't seem to build:
```
ncc: Version 0.22.3
ncc: Compiling file index.js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:130:10)
    at hashOf (/home/svenstaro/prj/upload-release-action/node_modules/@zeit/ncc/dist/ncc/index.js.cache.js:3:58216)
    at module.exports (/home/svenstaro/prj/upload-release-action/node_modules/@zeit/ncc/dist/ncc/index.js.cache.js:3:60642)
    at runCmd (/home/svenstaro/prj/upload-release-action/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:47355)
    at Object.819 (/home/svenstaro/prj/upload-release-action/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:44227)
    at __webpack_require__ (/home/svenstaro/prj/upload-release-action/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:169)
    at startup (/home/svenstaro/prj/upload-release-action/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:339)
    at module.exports.8 (/home/svenstaro/prj/upload-release-action/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:371)
    at /home/svenstaro/prj/upload-release-action/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:381 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```
Working on this.

**Comment by svenstaro** [comment]
Ok, I manually handled this on master. I'd like some testers and if it's all good, I'll cut a release.

**Comment by adambowles** [comment]
I'll test it but I don't know how to reference using the prerelease version :grimacing:

**Comment by shawaj** [comment]
Thanks so much @svenstaro - testing now :-)

**Comment by adambowles** [comment]
Runs without issue for me
Before (@v2): https://github.com/adambowles/cv/actions/runs/3832309801
After (@master): https://github.com/adambowles/cv/actions/runs/3833547618/

**Review by shawaj — APPROVED** [review]

**Comment by shawaj** [comment]
@svenstaro how's it looking for a release? Or do you need us to do any more testing?

**Comment by svenstaro** [comment]
This is now released.

**Comment by shawaj** [comment]
Thanks @svenstaro 

Sent you some sponsorship money. Thanks for all your efforts on this great action 👍

**Pull request closed without merging**
