### PR TITLE
fix #42 - overwrite body and name as well

### LINKED ISSUE #42: how to overwrite body?
overwrite: true
The asset with the same name will be overwritten, but not the body.
body: latest build time XXXXXXXX

### PR DESCRIPTION
**Pull request by regevbr**

### CODE REVIEW

**Review by svenstaro — APPROVED** [review]

**Comment by robertsLando** [comment]
This has broken all my builds.... I always used this action to upload assets in existing releases and this change made all my releases body empty. I would suggest to revert this change and make this opt-in instead, or at least, make this in a major release

**Comment by regevbr** [comment]
I think that the fix is to check if the body/name are not empty, and overwrite them only in that case, will that solve your case?

**Comment by regevbr** [comment]
see #108

**Comment by robertsLando** [comment]
Could be an alternative

**Comment by svenstaro** [comment]
True, I did see it as a bug fix at a time but now I see that users depended on that old behavior. At any rate, let's get this fixed quickly. I haven't received any feedback on #108. Does that work for you guys?

**Pull request merged**
